[package]
name = "r2dock"
version = "0.1.0"
authors = ["Téo Haÿs <teo.hays@protonmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "*", features = ["derive", "unicode"]}
dotenv = "*"
reqwest = {version = "*", features = ["blocking", "json"]}
json = "*"
crossbeam = "*"