#!/bin/bash

# debug
#echo $0
#for a in "$@"; do
#    printf "%s\n" "$a"
#done

if ! docker inspect container > /dev/null 2>&1; then
    echo "No running container on the machine. It might be stopped ?"
    exit 1
elif [[ -z "$@" ]]; then
    docker exec -it container /bin/bash
else
    case "$1" in
	"-c") shift;;
    esac
    docker exec container bash -c "$@"
fi
